export type Project = {
  id: string
  title: string
  category: 'featured' | 'voodoo' | 'studio' | 'personal'
  categoryLabel: string
  description: string
  tags: string[]
  links: { label: string; url: string }[]
  stats?: string
  featured?: boolean
  image?: string
}

export const projects: Project[] = [
  {
    id: 'editormind',
    title: 'EditorMind MCP',
    category: 'featured',
    categoryLabel: 'OPEN SOURCE',
    description: 'AI bridge tool that connects LLMs to Unity Editor via Model Context Protocol. Self-contained binaries — no Python/Node.js prerequisites. Built for autonomous AI playtesting and game dev automation.',
    tags: ['C#', 'TypeScript', 'MCP Protocol', 'Unity', 'AI Tooling', 'LLM'],
    links: [
      { label: 'GitHub', url: 'https://github.com/raheeb-ahmad' },
      { label: 'LinkedIn', url: 'https://www.linkedin.com/in/raheeb-ahmad/' },
    ],
    featured: true,
  },
  {
    id: 'hawala',
    title: 'The Hawala Network',
    category: 'featured',
    categoryLabel: 'STEAM GAME',
    description: 'Post-apocalyptic co-op FPS roguelite for 1–4 players. South Asian cultural aesthetics, low-poly dark visuals, cash-scavenging core loop. Built with Unity 6 URP.',
    tags: ['Unity 6 URP', 'FPS', 'Co-op', 'Roguelite', 'Steam', 'C#'],
    links: [
      { label: 'Steam (Coming Soon)', url: '#' },
    ],
    featured: true,
  },
  {
    id: 'light-fortress',
    title: 'Light Fortress',
    category: 'voodoo',
    categoryLabel: 'VOODOO PROTOTYPE',
    description: 'Strategically place powerful weapons to defend your tower from waves of enemies. Tower defense with deep upgrade mechanics.',
    tags: ['Unity', 'Mobile', 'Tower Defense', 'iOS'],
    links: [{ label: 'App Store', url: 'https://apps.apple.com/US/app/id6673906256' }],
    image: '/images/light-fortress.jpg',
  },
  {
    id: 'monkey-cannon',
    title: 'Monkey Cannon Mania',
    category: 'voodoo',
    categoryLabel: 'VOODOO PROTOTYPE',
    description: 'Control your crazy monkey as waves of enemies try to stand in your way. Wild coconut-smashing jungle action.',
    tags: ['Unity', 'Mobile', 'Arcade', 'iOS'],
    links: [{ label: 'App Store', url: 'https://apps.apple.com/US/app/id6737464231' }],
    image: '/images/monkey-cannon.jpg',
  },
  {
    id: 'capybara',
    title: 'Capybara Merge Clash',
    category: 'voodoo',
    categoryLabel: 'VOODOO PROTOTYPE',
    description: 'Merge capybara heroes, fight slimes, and master grid strategy in this fun RPG mobile game.',
    tags: ['Unity', 'Mobile', 'Merge', 'RPG', 'Android'],
    links: [{ label: 'Play Store', url: 'https://play.google.com/store/apps/details?id=com.MiniSports.capybaramergeclash' }],
    image: '/images/capybara-merge.jpg',
  },
  {
    id: 'house-makeover',
    title: 'House Makeover',
    category: 'studio',
    categoryLabel: 'GAME DISTRICT',
    description: 'ASMR house renovation game with calming sounds and satisfying cleanup mechanics.',
    tags: ['Unity', 'Mobile', 'Hyper-casual', 'Android'],
    stats: '10M+ Downloads',
    links: [{ label: 'Play Store', url: 'https://play.google.com/store/apps/details?id=com.gps.housemakeover.satisfying.clean' }],
    image: '/images/house-makeover.jpg',
  },
  {
    id: 'smash-frustrating',
    title: 'Smash Frustrating Guy',
    category: 'studio',
    categoryLabel: 'GAME DISTRICT',
    description: 'Become the ultimate smasher and take on irritating characters in hilarious scenarios.',
    tags: ['Unity', 'Mobile', 'Hyper-casual', 'Android'],
    stats: '10M+ Downloads',
    links: [],
  },
  {
    id: 'build-house-tycoon',
    title: 'Build House Tycoon',
    category: 'studio',
    categoryLabel: 'GENITEAM',
    description: 'Build and design your dream house in this satisfying tycoon experience.',
    tags: ['Unity', 'Mobile', 'Tycoon', 'Android'],
    stats: '100K+ Downloads',
    links: [{ label: 'Play Store', url: 'https://play.google.com/store/apps/details?id=com.genigames.build.house.tycoon' }],
    image: '/images/build-house-tycoon.jpg',
  },
  {
    id: 'scary-teacher',
    title: 'Scary Teacher 3D',
    category: 'studio',
    categoryLabel: 'GENITEAM',
    description: 'Contributed to new events, mechanics improvements, and mini-games for one of the most popular games on mobile.',
    tags: ['Unity', 'Mobile', 'Action', 'Android/iOS'],
    stats: '100M+ Downloads',
    links: [{ label: 'Play Store', url: 'https://play.google.com/store/apps/details?id=com.zakg.scaryteacher.hellgame' }],
    image: '/images/scary-teacher.jpg',
  },
  {
    id: 'school-escape',
    title: 'School Escape',
    category: 'personal',
    categoryLabel: 'PERSONAL',
    description: 'Escape from a haunted school filled with ghost witches. A tense survival horror experience.',
    tags: ['Unity', 'Survival', 'Horror', 'itch.io'],
    links: [{ label: 'itch.io', url: 'https://rfantasy.itch.io/school-escape' }],
    image: '/images/school-escape.jpg',
  },
  {
    id: 'dark-adventure',
    title: 'Dark Adventure',
    category: 'personal',
    categoryLabel: 'PERSONAL',
    description: 'Save the Queen from the Boss Skeleton in this dark fantasy adventure.',
    tags: ['Unity', 'Adventure', 'Fantasy', 'itch.io'],
    links: [{ label: 'itch.io', url: 'https://rfantasy.itch.io/dark-adventure' }],
    image: '/images/dark-adventure.jpg',
  },
  {
    id: 'shattered-fate',
    title: 'Shattered Fate',
    category: 'personal',
    categoryLabel: 'PERSONAL',
    description: 'An action-adventure game set in a world torn apart by a shattered timeline. Fight to restore what was broken.',
    tags: ['Unity', 'Action', 'Adventure', 'itch.io'],
    links: [{ label: 'itch.io', url: 'https://rfantasy.itch.io/shattered-fate' }],
    image: '/images/shattered-fate.jpg',
  },
  {
    id: 'code-quest',
    title: 'Code Quest',
    category: 'personal',
    categoryLabel: 'PERSONAL',
    description: 'Learn basics of C# while playing RPG Adventure Game.',
    tags: ['Unity', 'Education', 'RPG', 'itch.io'],
    links: [{ label: 'itch.io', url: 'https://rfantasy.itch.io/code-quest' }],
    image: '/images/code-quest.jpg',
  },
  {
    id: 'english-quest',
    title: 'English Quest',
    category: 'personal',
    categoryLabel: 'PERSONAL',
    description: 'Unique RPG English Learning Game.',
    tags: ['Unity', 'Education', 'RPG', 'itch.io'],
    links: [{ label: 'itch.io', url: 'https://rfantasy.itch.io/english-quest' }],
    image: '/images/english-quest.jpg',
  },
]
